version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=5001    #默认的管理端口，建议更改一个其他数字，否则会出现webui报错情况（Unauthorized ）
    volumes:
      - /mnt/docker/qb/config:/config           #qBittorrent数据配置路径
      - /mnt/docker/qb/downloads:/downloads            #qBittorrent的下载目录
    ports:
      - 18080:8080                  #qBittorrent的webui访问端口，如果有外网访问需求
      - 6881:6881                   #qBittorrent的传入链接监听端口，需要路由器中转发
      - 6881:6881/udp               #qBittorrent的传入链接监听端口，需要路由器中转发
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: "host"
    volumes:
      - /mnt/docker/jf/config:/config
      - /mnt/docker/jf/cache:/cache
      - /mnt/docker/jf/media:/media
      - /mnt/docker/jf/media2:/media2:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com

  nas-tools:
    image: 318182456/nas-tools
    container_name: nastools
    user: uid:gid
    network_mode: "host"
    volumes:
      - /mnt/docker/nastools/config:/config             # 冒号左边请修改为你想在主机上保存配置文件的路径  
      - /mnt/docker/nastools/tv:/volume/tv         # 媒体目录，多个目录需要分别映射进来
      - /mnt/docker/nastools/movie:/volume/movie         # 媒体目录，多个目录需要分别映射进来
      - /mnt/docker/nastools/media2:/media2:ro
    ports:
      - 3000:3000
    environment:
      - PUID=0                        # 想切换为哪个用户来运行程序，该用户的uid，详见下方说明
      - PGID=0                        # 想切换为哪个用户来运行程序，该用户的gid，详见下方说明`  
      - UMASK=000                     # 掩码权限，默认000，可以考虑设置为022` 
      - WEBUI_PORT=3000               # 默认的管理端口，建议更改一个其他数字，否则会出现webui报错情况（Unauthorized ）
      - NASTOOL_AUTO_UPDATE=false     # 如需在启动容器时自动升级程程序请设置为true`   
      - NASTOOL_CN_UPDATE=false       # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
    restart: "unless-stopped"

